library('survival')
#if(!require(devtools)) install.packages("devtools")
#devtools::install_github("kassambara/survminer", build_vignettes = FALSE)
library('survminer')
library('tidyr')
surdata=read.table("C:/Users/shristi/Documents/survival analysis prac data/CGGA.mRNAseq_693_clinical.20200506.txt",sep="\t",header = T,row.names = 1)
print(head(surdata))
fit = survfit(Surv(OS,Censor.alive.0.dead.1.) ~ Gender,data = surdata)
fit
ggsurvplot(fit, data= surdata)
ggsurvplot(fit, data= surdata, surv.median.line = 'hv')
install.packages("markdown")
library(markdown)
ggsurvplot(fit,data=surdata,surv.median.line = 'hv',pval = T, risk.table = T)
